import React, { useContext } from "react";
import { Row, Col, Card } from "antd";
import { Link } from "react-router-dom";
import moment from "moment";
import { useGetNftQuery } from "../services/cryptoNFTAPI";
import { ConnectWalletContext } from "../context/ConnectWalletContext";
import SearchBar from "../utils/SearchBar";

const NFTTokens = () => {
  const { connectedAccount } = useContext(ConnectWalletContext);
  const [searchToken, setSearchToken] = React.useState("");
  //this hook is generated by redux ToolKit and get it under from the services component
  const { data: cryptoNFTList, isFetching } = useGetNftQuery(
    searchToken ?? connectedAccount
  );

  //store the searchAccount into the state
  const onSearchAccount = (searchAccount) => {
    setSearchToken(searchAccount);
  };

  return (
    <div>
      <h5 style={{ marginLeft: "20rem" }}>Looking for NFT Tokens</h5>
      <SearchBar searchAccount={onSearchAccount} />
      {connectedAccount.length > 0 ? (
        <>
          {!isFetching ? (
            <>
              {cryptoNFTList !== undefined ? (
                <>
                  <div>
                    <h1 className="crypto-heading-container">
                      List of NFT tokens
                    </h1>
                  </div>
                  <Row gutter={[32, 32]} className="crypto-card-container">
                    {cryptoNFTList?.assets?.length > 0 ? (
                      <>
                        {cryptoNFTList?.assets?.map((nftItems, index) => (
                          <Col
                            xs={24}
                            sm={12}
                            lg={6}
                            className="crypto-card"
                            key={index}
                          >
                            <a
                              href={nftItems.permalink}
                              target="_blank"
                              rel="noreferrer"
                            >
                              <Card
                                style={{
                                  width: "100%",
                                  height: "100%",
                                  borderBlockColor: "cyan",
                                }}
                                title={`${
                                  nftItems?.asset_contract?.name ??
                                  nftItems?.name ??
                                  ""
                                } `}
                                hoverable
                              >
                                <img
                                  style={{
                                    marginLeft: "1rem",
                                    height: "10rem",
                                    width: "10rem",
                                    marginBottom: "1rem",
                                  }}
                                  src={`${nftItems?.image_url ?? ""}`}
                                  alt=""
                                />

                                <p>
                                  Symbol:{" "}
                                  {nftItems?.asset_contract?.symbol ?? ""}
                                </p>
                                <p>
                                  Description:{" "}
                                  {nftItems?.description?.length > 50
                                    ? `${nftItems?.description?.substring(
                                        0,
                                        50
                                      )},.`
                                    : nftItems?.description}
                                </p>
                                <p>
                                  CreateDate:{" "}
                                  {moment(
                                    nftItems?.asset_contract?.created_date
                                  ).format("MM/DD/YYYY")}
                                </p>
                                <p>
                                  ClosingDate:{" "}
                                  {moment(
                                    nftItems?.asset_contract?.closing_date
                                  ).format("MM/DD/YYYY")}
                                </p>
                              </Card>
                            </a>
                          </Col>
                        ))}
                      </>
                    ) : (
                      ""
                    )}
                  </Row>
                </>
              ) : (
                <div style={{ marginLeft: "20rem" }}>
                  <h1>No NFT token found for the connected wallet user</h1>
                  <div style={{ marginLeft: "1rem" }}>
                    <h3>{connectedAccount}</h3>
                  </div>
                </div>
              )}
            </>
          ) : (
            <div style={{ marginLeft: "22rem" }}>
              <h3>Loading...</h3>
            </div>
          )}
        </>
      ) : (
        ""
      )}
    </div>
  );
};

export default NFTTokens;
